/**
 * This file was generated by arcli. This file when found in your Reactium
 * instance, will produce a UMD (Universal Module Definition) module,
 * named syndicate.js, produced in public/assets/js/umd/syndicate by default.
 *
 * To develop this plugin, make your development changes to index.js, not here.
 */
require('./index');
