export const fileExtensions = [
    { type: 'image', value: 'jpg' },
    { type: 'image', value: 'png' },
    { type: 'image', value: 'gif' },
    { type: 'image', value: 'webp' },
    { type: 'image', value: 'svg' },
    { type: 'video', value: 'mp4' },
    { type: 'video', value: 'mpg' },
    { type: 'video', value: 'mov' },
    { type: 'video', value: 'wmv' },
    { type: 'video', value: 'avi' },
    { type: 'audio', value: 'mp3' },
    { type: 'audio', value: 'wav' },
    { type: 'audio', value: 'pcm' },
    { type: 'audio', value: 'aac' },
    { type: 'audio', value: 'ogg' },
    { type: 'audio', value: 'wma' },
    { type: 'document', value: 'pdf' },
    { type: 'document', value: 'xls' },
    { type: 'document', value: 'xlsx' },
    { type: 'document', value: 'doc' },
    { type: 'document', value: 'docx' },
    { type: 'document', value: 'ppt' },
    { type: 'document', value: 'pptx' },
    { type: 'document', value: 'txt' },
    { type: 'archive', value: 'zip' },
    { type: 'archive', value: 'zipx' },
    { type: 'archive', value: 'rar' },
    { type: 'archive', value: 'tar.gz' },
];

export default fileExtensions;
