// THIS FILE IS GENERATED BY THE `$ arcli icons` command
// DO NOT DIRECTLY EDIT !!!!!!!!!!!!!!!!

import Home from './svgs/Home';
import Home2 from './svgs/Home2';
import Home3 from './svgs/Home3';
import Home4 from './svgs/Home4';
import Home5 from './svgs/Home5';
import Home6 from './svgs/Home6';
import Bathtub from './svgs/Bathtub';
import Toothbrush from './svgs/Toothbrush';
import Bed from './svgs/Bed';
import Couch from './svgs/Couch';
import Chair from './svgs/Chair';
import City from './svgs/City';
import Apartment from './svgs/Apartment';
import Pencil from './svgs/Pencil';
import Pencil2 from './svgs/Pencil2';
import Pen from './svgs/Pen';
import Pencil3 from './svgs/Pencil3';
import Eraser from './svgs/Eraser';
import Pencil4 from './svgs/Pencil4';
import Pencil5 from './svgs/Pencil5';
import Feather from './svgs/Feather';
import Feather2 from './svgs/Feather2';
import Feather3 from './svgs/Feather3';
import Pen2 from './svgs/Pen2';
import PenAdd from './svgs/PenAdd';
import PenRemove from './svgs/PenRemove';
import Vector from './svgs/Vector';
import Pen3 from './svgs/Pen3';
import Blog from './svgs/Blog';
import Brush from './svgs/Brush';
import Brush2 from './svgs/Brush2';
import Spray from './svgs/Spray';
import PaintRoller from './svgs/PaintRoller';
import Stamp from './svgs/Stamp';
import Tape from './svgs/Tape';
import DeskTape from './svgs/DeskTape';
import Texture from './svgs/Texture';
import EyeDropper from './svgs/EyeDropper';
import Palette from './svgs/Palette';
import ColorSampler from './svgs/ColorSampler';
import Bucket from './svgs/Bucket';
import Gradient from './svgs/Gradient';
import Gradient2 from './svgs/Gradient2';
import MagicWand from './svgs/MagicWand';
import Magnet from './svgs/Magnet';
import PencilRuler from './svgs/PencilRuler';
import PencilRuler2 from './svgs/PencilRuler2';
import Compass from './svgs/Compass';
import Aim from './svgs/Aim';
import Gun from './svgs/Gun';
import Bottle from './svgs/Bottle';
import Drop from './svgs/Drop';
import DropCrossed from './svgs/DropCrossed';
import Drop2 from './svgs/Drop2';
import Snow from './svgs/Snow';
import Snow2 from './svgs/Snow2';
import Fire from './svgs/Fire';
import Lighter from './svgs/Lighter';
import Knife from './svgs/Knife';
import Dagger from './svgs/Dagger';
import Tissue from './svgs/Tissue';
import ToiletPaper from './svgs/ToiletPaper';
import Poop from './svgs/Poop';
import Umbrella from './svgs/Umbrella';
import Umbrella2 from './svgs/Umbrella2';
import Rain from './svgs/Rain';
import Tornado from './svgs/Tornado';
import Wind from './svgs/Wind';
import Fan from './svgs/Fan';
import Contrast from './svgs/Contrast';
import SunSmall from './svgs/SunSmall';
import Sun from './svgs/Sun';
import Sun2 from './svgs/Sun2';
import Moon from './svgs/Moon';
import Cloud from './svgs/Cloud';
import CloudUpload from './svgs/CloudUpload';
import CloudDownload from './svgs/CloudDownload';
import CloudRain from './svgs/CloudRain';
import CloudHailstones from './svgs/CloudHailstones';
import CloudSnow from './svgs/CloudSnow';
import CloudWindy from './svgs/CloudWindy';
import SunWind from './svgs/SunWind';
import CloudFog from './svgs/CloudFog';
import CloudSun from './svgs/CloudSun';
import CloudLightning from './svgs/CloudLightning';
import CloudSync from './svgs/CloudSync';
import CloudLock from './svgs/CloudLock';
import CloudGear from './svgs/CloudGear';
import CloudAlert from './svgs/CloudAlert';
import CloudCheck from './svgs/CloudCheck';
import CloudCross from './svgs/CloudCross';
import CloudCrossed from './svgs/CloudCrossed';
import CloudDatabase from './svgs/CloudDatabase';
import Database from './svgs/Database';
import DatabaseAdd from './svgs/DatabaseAdd';
import DatabaseRemove from './svgs/DatabaseRemove';
import DatabaseLock from './svgs/DatabaseLock';
import DatabaseRefresh from './svgs/DatabaseRefresh';
import DatabaseCheck from './svgs/DatabaseCheck';
import DatabaseHistory from './svgs/DatabaseHistory';
import DatabaseUpload from './svgs/DatabaseUpload';
import DatabaseDownload from './svgs/DatabaseDownload';
import Server from './svgs/Server';
import Shield from './svgs/Shield';
import ShieldCheck from './svgs/ShieldCheck';
import ShieldAlert from './svgs/ShieldAlert';
import ShieldCross from './svgs/ShieldCross';
import Lock from './svgs/Lock';
import RotationLock from './svgs/RotationLock';
import Unlock from './svgs/Unlock';
import Key from './svgs/Key';
import KeyHole from './svgs/KeyHole';
import ToggleOff from './svgs/ToggleOff';
import ToggleOn from './svgs/ToggleOn';
import Cog from './svgs/Cog';
import Cog2 from './svgs/Cog2';
import Wrench from './svgs/Wrench';
import Screwdriver from './svgs/Screwdriver';
import HammerWrench from './svgs/HammerWrench';
import Hammer from './svgs/Hammer';
import Saw from './svgs/Saw';
import Axe from './svgs/Axe';
import Axe2 from './svgs/Axe2';
import Shovel from './svgs/Shovel';
import Pickaxe from './svgs/Pickaxe';
import Factory from './svgs/Factory';
import Factory2 from './svgs/Factory2';
import Recycle from './svgs/Recycle';
import Trash from './svgs/Trash';
import Trash2 from './svgs/Trash2';
import Trash3 from './svgs/Trash3';
import Broom from './svgs/Broom';
import Game from './svgs/Game';
import Gamepad from './svgs/Gamepad';
import Joystick from './svgs/Joystick';
import Dice from './svgs/Dice';
import Spades from './svgs/Spades';
import Diamonds from './svgs/Diamonds';
import Clubs from './svgs/Clubs';
import Hearts from './svgs/Hearts';
import Heart from './svgs/Heart';
import Star from './svgs/Star';
import StarHalf from './svgs/StarHalf';
import StarEmpty from './svgs/StarEmpty';
import Flag from './svgs/Flag';
import Flag2 from './svgs/Flag2';
import Flag3 from './svgs/Flag3';
import MailboxFull from './svgs/MailboxFull';
import MailboxEmpty from './svgs/MailboxEmpty';
import AtSign from './svgs/AtSign';
import Envelope from './svgs/Envelope';
import EnvelopeOpen from './svgs/EnvelopeOpen';
import Paperclip from './svgs/Paperclip';
import PaperPlane from './svgs/PaperPlane';
import Reply from './svgs/Reply';
import ReplyAll from './svgs/ReplyAll';
import Inbox from './svgs/Inbox';
import Inbox2 from './svgs/Inbox2';
import Outbox from './svgs/Outbox';
import Box from './svgs/Box';
import Archive from './svgs/Archive';
import Archive2 from './svgs/Archive2';
import Drawers from './svgs/Drawers';
import Drawers2 from './svgs/Drawers2';
import Drawers3 from './svgs/Drawers3';
import Eye from './svgs/Eye';
import EyeCrossed from './svgs/EyeCrossed';
import EyePlus from './svgs/EyePlus';
import EyeMinus from './svgs/EyeMinus';
import Binoculars from './svgs/Binoculars';
import Binoculars2 from './svgs/Binoculars2';
import Hdd from './svgs/Hdd';
import HddDown from './svgs/HddDown';
import HddUp from './svgs/HddUp';
import FloppyDisk from './svgs/FloppyDisk';
import Disc from './svgs/Disc';
import Tape2 from './svgs/Tape2';
import Printer from './svgs/Printer';
import Shredder from './svgs/Shredder';
import FileEmpty from './svgs/FileEmpty';
import FileAdd from './svgs/FileAdd';
import FileCheck from './svgs/FileCheck';
import FileLock from './svgs/FileLock';
import Files from './svgs/Files';
import Copy from './svgs/Copy';
import Compare from './svgs/Compare';
import Folder from './svgs/Folder';
import FolderSearch from './svgs/FolderSearch';
import FolderPlus from './svgs/FolderPlus';
import FolderMinus from './svgs/FolderMinus';
import FolderDownload from './svgs/FolderDownload';
import FolderUpload from './svgs/FolderUpload';
import FolderStar from './svgs/FolderStar';
import FolderHeart from './svgs/FolderHeart';
import FolderUser from './svgs/FolderUser';
import FolderShared from './svgs/FolderShared';
import FolderMusic from './svgs/FolderMusic';
import FolderPicture from './svgs/FolderPicture';
import FolderFilm from './svgs/FolderFilm';
import Scissors from './svgs/Scissors';
import Paste from './svgs/Paste';
import ClipboardEmpty from './svgs/ClipboardEmpty';
import ClipboardPencil from './svgs/ClipboardPencil';
import ClipboardText from './svgs/ClipboardText';
import ClipboardCheck from './svgs/ClipboardCheck';
import ClipboardDown from './svgs/ClipboardDown';
import ClipboardLeft from './svgs/ClipboardLeft';
import ClipboardAlert from './svgs/ClipboardAlert';
import ClipboardUser from './svgs/ClipboardUser';
import Register from './svgs/Register';
import Enter from './svgs/Enter';
import Exit from './svgs/Exit';
import Papers from './svgs/Papers';
import News from './svgs/News';
import Reading from './svgs/Reading';
import Typewriter from './svgs/Typewriter';
import Document from './svgs/Document';
import Document2 from './svgs/Document2';
import GraduationHat from './svgs/GraduationHat';
import License from './svgs/License';
import License2 from './svgs/License2';
import MedalEmpty from './svgs/MedalEmpty';
import MedalFirst from './svgs/MedalFirst';
import MedalSecond from './svgs/MedalSecond';
import MedalThird from './svgs/MedalThird';
import Podium from './svgs/Podium';
import Trophy from './svgs/Trophy';
import Trophy2 from './svgs/Trophy2';
import MusicNote from './svgs/MusicNote';
import MusicNote2 from './svgs/MusicNote2';
import MusicNote3 from './svgs/MusicNote3';
import Playlist from './svgs/Playlist';
import PlaylistAdd from './svgs/PlaylistAdd';
import Guitar from './svgs/Guitar';
import Trumpet from './svgs/Trumpet';
import Album from './svgs/Album';
import Shuffle from './svgs/Shuffle';
import RepeatOne from './svgs/RepeatOne';
import Repeat from './svgs/Repeat';
import Headphones from './svgs/Headphones';
import Headset from './svgs/Headset';
import Loudspeaker from './svgs/Loudspeaker';
import Equalizer from './svgs/Equalizer';
import Theater from './svgs/Theater';
import ThreeDGlasses from './svgs/ThreeDGlasses';
import Ticket from './svgs/Ticket';
import Presentation from './svgs/Presentation';
import Play from './svgs/Play';
import FilmPlay from './svgs/FilmPlay';
import ClapboardPlay from './svgs/ClapboardPlay';
import Media from './svgs/Media';
import Film from './svgs/Film';
import Film2 from './svgs/Film2';
import Surveillance from './svgs/Surveillance';
import Surveillance2 from './svgs/Surveillance2';
import Camera from './svgs/Camera';
import CameraCrossed from './svgs/CameraCrossed';
import CameraPlay from './svgs/CameraPlay';
import TimeLapse from './svgs/TimeLapse';
import Record from './svgs/Record';
import Camera2 from './svgs/Camera2';
import CameraFlip from './svgs/CameraFlip';
import Panorama from './svgs/Panorama';
import TimeLapse2 from './svgs/TimeLapse2';
import Shutter from './svgs/Shutter';
import Shutter2 from './svgs/Shutter2';
import FaceDetection from './svgs/FaceDetection';
import Flare from './svgs/Flare';
import Convex from './svgs/Convex';
import Concave from './svgs/Concave';
import Picture from './svgs/Picture';
import Picture2 from './svgs/Picture2';
import Picture3 from './svgs/Picture3';
import Pictures from './svgs/Pictures';
import Book from './svgs/Book';
import AudioBook from './svgs/AudioBook';
import Book2 from './svgs/Book2';
import Bookmark from './svgs/Bookmark';
import Bookmark2 from './svgs/Bookmark2';
import Label from './svgs/Label';
import Library from './svgs/Library';
import Library2 from './svgs/Library2';
import Contacts from './svgs/Contacts';
import Profile from './svgs/Profile';
import Portrait from './svgs/Portrait';
import Portrait2 from './svgs/Portrait2';
import User from './svgs/User';
import UserPlus from './svgs/UserPlus';
import UserMinus from './svgs/UserMinus';
import UserLock from './svgs/UserLock';
import Users from './svgs/Users';
import Users2 from './svgs/Users2';
import UsersPlus from './svgs/UsersPlus';
import UsersMinus from './svgs/UsersMinus';
import GroupWork from './svgs/GroupWork';
import Woman from './svgs/Woman';
import Man from './svgs/Man';
import Baby from './svgs/Baby';
import Baby2 from './svgs/Baby2';
import Baby3 from './svgs/Baby3';
import BabyBottle from './svgs/BabyBottle';
import Walk from './svgs/Walk';
import HandWaving from './svgs/HandWaving';
import Jump from './svgs/Jump';
import Run from './svgs/Run';
import Woman2 from './svgs/Woman2';
import Man2 from './svgs/Man2';
import ManWoman from './svgs/ManWoman';
import Height from './svgs/Height';
import Weight from './svgs/Weight';
import Scale from './svgs/Scale';
import Button from './svgs/Button';
import BowTie from './svgs/BowTie';
import Tie from './svgs/Tie';
import Socks from './svgs/Socks';
import Shoe from './svgs/Shoe';
import Shoes from './svgs/Shoes';
import Hat from './svgs/Hat';
import Pants from './svgs/Pants';
import Shorts from './svgs/Shorts';
import FlipFlops from './svgs/FlipFlops';
import Shirt from './svgs/Shirt';
import Hanger from './svgs/Hanger';
import Laundry from './svgs/Laundry';
import Store from './svgs/Store';
import Haircut from './svgs/Haircut';
import Store24 from './svgs/Store24';
import Barcode from './svgs/Barcode';
import Barcode2 from './svgs/Barcode2';
import Barcode3 from './svgs/Barcode3';
import Cashier from './svgs/Cashier';
import Bag from './svgs/Bag';
import Bag2 from './svgs/Bag2';
import Cart from './svgs/Cart';
import CartEmpty from './svgs/CartEmpty';
import CartFull from './svgs/CartFull';
import CartPlus from './svgs/CartPlus';
import CartPlus2 from './svgs/CartPlus2';
import CartAdd from './svgs/CartAdd';
import CartRemove from './svgs/CartRemove';
import CartExchange from './svgs/CartExchange';
import Tag from './svgs/Tag';
import Tags from './svgs/Tags';
import Receipt from './svgs/Receipt';
import Wallet from './svgs/Wallet';
import CreditCard from './svgs/CreditCard';
import CashDollar from './svgs/CashDollar';
import CashEuro from './svgs/CashEuro';
import CashPound from './svgs/CashPound';
import CashYen from './svgs/CashYen';
import BagDollar from './svgs/BagDollar';
import BagEuro from './svgs/BagEuro';
import BagPound from './svgs/BagPound';
import BagYen from './svgs/BagYen';
import CoinDollar from './svgs/CoinDollar';
import CoinEuro from './svgs/CoinEuro';
import CoinPound from './svgs/CoinPound';
import CoinYen from './svgs/CoinYen';
import Calculator from './svgs/Calculator';
import Calculator2 from './svgs/Calculator2';
import Abacus from './svgs/Abacus';
import Vault from './svgs/Vault';
import Telephone from './svgs/Telephone';
import PhoneLock from './svgs/PhoneLock';
import PhoneWave from './svgs/PhoneWave';
import PhonePause from './svgs/PhonePause';
import PhoneOutgoing from './svgs/PhoneOutgoing';
import PhoneIncoming from './svgs/PhoneIncoming';
import PhoneInOut from './svgs/PhoneInOut';
import PhoneError from './svgs/PhoneError';
import PhoneSip from './svgs/PhoneSip';
import PhonePlus from './svgs/PhonePlus';
import PhoneMinus from './svgs/PhoneMinus';
import Voicemail from './svgs/Voicemail';
import Dial from './svgs/Dial';
import Telephone2 from './svgs/Telephone2';
import Pushpin from './svgs/Pushpin';
import Pushpin2 from './svgs/Pushpin2';
import MapMarker from './svgs/MapMarker';
import MapMarkerUser from './svgs/MapMarkerUser';
import MapMarkerDown from './svgs/MapMarkerDown';
import MapMarkerCheck from './svgs/MapMarkerCheck';
import MapMarkerCrossed from './svgs/MapMarkerCrossed';
import Radar from './svgs/Radar';
import Compass2 from './svgs/Compass2';
import Map from './svgs/Map';
import Map2 from './svgs/Map2';
import Location from './svgs/Location';
import RoadSign from './svgs/RoadSign';
import CalendarEmpty from './svgs/CalendarEmpty';
import CalendarCheck from './svgs/CalendarCheck';
import CalendarCross from './svgs/CalendarCross';
import Calendar31 from './svgs/Calendar31';
import CalendarFull from './svgs/CalendarFull';
import CalendarInsert from './svgs/CalendarInsert';
import CalendarText from './svgs/CalendarText';
import CalendarUser from './svgs/CalendarUser';
import Mouse from './svgs/Mouse';
import MouseLeft from './svgs/MouseLeft';
import MouseRight from './svgs/MouseRight';
import MouseBoth from './svgs/MouseBoth';
import Keyboard from './svgs/Keyboard';
import KeyboardUp from './svgs/KeyboardUp';
import KeyboardDown from './svgs/KeyboardDown';
import Delete from './svgs/Delete';
import SpellCheck from './svgs/SpellCheck';
import Escape from './svgs/Escape';
import Enter2 from './svgs/Enter2';
import Screen from './svgs/Screen';
import AspectRatio from './svgs/AspectRatio';
import Signal from './svgs/Signal';
import SignalLock from './svgs/SignalLock';
import Signal80 from './svgs/Signal80';
import Signal60 from './svgs/Signal60';
import Signal40 from './svgs/Signal40';
import Signal20 from './svgs/Signal20';
import Signal0 from './svgs/Signal0';
import SignalBlocked from './svgs/SignalBlocked';
import Sim from './svgs/Sim';
import FlashMemory from './svgs/FlashMemory';
import UsbDrive from './svgs/UsbDrive';
import Phone from './svgs/Phone';
import Smartphone from './svgs/Smartphone';
import SmartphoneNotification from './svgs/SmartphoneNotification';
import SmartphoneVibration from './svgs/SmartphoneVibration';
import SmartphoneEmbed from './svgs/SmartphoneEmbed';
import SmartphoneWaves from './svgs/SmartphoneWaves';
import Tablet from './svgs/Tablet';
import Tablet2 from './svgs/Tablet2';
import Laptop from './svgs/Laptop';
import LaptopPhone from './svgs/LaptopPhone';
import Desktop from './svgs/Desktop';
import Launch from './svgs/Launch';
import NewTab from './svgs/NewTab';
import Window from './svgs/Window';
import Cable from './svgs/Cable';
import Cable2 from './svgs/Cable2';
import Tv from './svgs/Tv';
import Radio from './svgs/Radio';
import RemoteControl from './svgs/RemoteControl';
import PowerSwitch from './svgs/PowerSwitch';
import Power from './svgs/Power';
import PowerCrossed from './svgs/PowerCrossed';
import FlashAuto from './svgs/FlashAuto';
import Lamp from './svgs/Lamp';
import Flashlight from './svgs/Flashlight';
import Lampshade from './svgs/Lampshade';
import Cord from './svgs/Cord';
import Outlet from './svgs/Outlet';
import BatteryPower from './svgs/BatteryPower';
import BatteryEmpty from './svgs/BatteryEmpty';
import BatteryAlert from './svgs/BatteryAlert';
import BatteryError from './svgs/BatteryError';
import BatteryLow1 from './svgs/BatteryLow1';
import BatteryLow2 from './svgs/BatteryLow2';
import BatteryLow3 from './svgs/BatteryLow3';
import BatteryMid1 from './svgs/BatteryMid1';
import BatteryMid2 from './svgs/BatteryMid2';
import BatteryMid3 from './svgs/BatteryMid3';
import BatteryFull from './svgs/BatteryFull';
import BatteryCharging from './svgs/BatteryCharging';
import BatteryCharging2 from './svgs/BatteryCharging2';
import BatteryCharging3 from './svgs/BatteryCharging3';
import BatteryCharging4 from './svgs/BatteryCharging4';
import BatteryCharging5 from './svgs/BatteryCharging5';
import BatteryCharging6 from './svgs/BatteryCharging6';
import BatteryCharging7 from './svgs/BatteryCharging7';
import Chip from './svgs/Chip';
import ChipX64 from './svgs/ChipX64';
import ChipX86 from './svgs/ChipX86';
import Bubble from './svgs/Bubble';
import Bubbles from './svgs/Bubbles';
import BubbleDots from './svgs/BubbleDots';
import BubbleAlert from './svgs/BubbleAlert';
import BubbleQuestion from './svgs/BubbleQuestion';
import BubbleText from './svgs/BubbleText';
import BubblePencil from './svgs/BubblePencil';
import BubblePicture from './svgs/BubblePicture';
import BubbleVideo from './svgs/BubbleVideo';
import BubbleUser from './svgs/BubbleUser';
import BubbleQuote from './svgs/BubbleQuote';
import BubbleHeart from './svgs/BubbleHeart';
import BubbleEmoticon from './svgs/BubbleEmoticon';
import BubbleAttachment from './svgs/BubbleAttachment';
import PhoneBubble from './svgs/PhoneBubble';
import QuoteOpen from './svgs/QuoteOpen';
import QuoteClose from './svgs/QuoteClose';
import Dna from './svgs/Dna';
import HeartPulse from './svgs/HeartPulse';
import Pulse from './svgs/Pulse';
import Syringe from './svgs/Syringe';
import Pills from './svgs/Pills';
import FirstAid from './svgs/FirstAid';
import Lifebuoy from './svgs/Lifebuoy';
import Bandage from './svgs/Bandage';
import Bandages from './svgs/Bandages';
import Thermometer from './svgs/Thermometer';
import Microscope from './svgs/Microscope';
import Brain from './svgs/Brain';
import Beaker from './svgs/Beaker';
import Skull from './svgs/Skull';
import Bone from './svgs/Bone';
import Construction from './svgs/Construction';
import ConstructionCone from './svgs/ConstructionCone';
import PieChart from './svgs/PieChart';
import PieChart2 from './svgs/PieChart2';
import Graph from './svgs/Graph';
import ChartGrowth from './svgs/ChartGrowth';
import ChartBars from './svgs/ChartBars';
import ChartSettings from './svgs/ChartSettings';
import Cake from './svgs/Cake';
import Gift from './svgs/Gift';
import Balloon from './svgs/Balloon';
import Rank from './svgs/Rank';
import Rank2 from './svgs/Rank2';
import Rank3 from './svgs/Rank3';
import Crown from './svgs/Crown';
import Lotus from './svgs/Lotus';
import Diamond from './svgs/Diamond';
import Diamond2 from './svgs/Diamond2';
import Diamond3 from './svgs/Diamond3';
import Diamond4 from './svgs/Diamond4';
import Linearicons from './svgs/Linearicons';
import Teacup from './svgs/Teacup';
import Teapot from './svgs/Teapot';
import Glass from './svgs/Glass';
import Bottle2 from './svgs/Bottle2';
import GlassCocktail from './svgs/GlassCocktail';
import Glass2 from './svgs/Glass2';
import Dinner from './svgs/Dinner';
import Dinner2 from './svgs/Dinner2';
import Chef from './svgs/Chef';
import Scale2 from './svgs/Scale2';
import Egg from './svgs/Egg';
import Egg2 from './svgs/Egg2';
import Eggs from './svgs/Eggs';
import Platter from './svgs/Platter';
import Steak from './svgs/Steak';
import Hamburger from './svgs/Hamburger';
import Hotdog from './svgs/Hotdog';
import Pizza from './svgs/Pizza';
import Sausage from './svgs/Sausage';
import Chicken from './svgs/Chicken';
import Fish from './svgs/Fish';
import Carrot from './svgs/Carrot';
import Cheese from './svgs/Cheese';
import Bread from './svgs/Bread';
import IceCream from './svgs/IceCream';
import IceCream2 from './svgs/IceCream2';
import Candy from './svgs/Candy';
import Lollipop from './svgs/Lollipop';
import CoffeeBean from './svgs/CoffeeBean';
import CoffeeCup from './svgs/CoffeeCup';
import Cherry from './svgs/Cherry';
import Grapes from './svgs/Grapes';
import Citrus from './svgs/Citrus';
import Apple from './svgs/Apple';
import Leaf from './svgs/Leaf';
import Landscape from './svgs/Landscape';
import PineTree from './svgs/PineTree';
import Tree from './svgs/Tree';
import Cactus from './svgs/Cactus';
import Paw from './svgs/Paw';
import Footprint from './svgs/Footprint';
import SpeedSlow from './svgs/SpeedSlow';
import SpeedMedium from './svgs/SpeedMedium';
import SpeedFast from './svgs/SpeedFast';
import Rocket from './svgs/Rocket';
import Hammer2 from './svgs/Hammer2';
import Balance from './svgs/Balance';
import Briefcase from './svgs/Briefcase';
import LuggageWeight from './svgs/LuggageWeight';
import Dolly from './svgs/Dolly';
import Plane from './svgs/Plane';
import PlaneCrossed from './svgs/PlaneCrossed';
import Helicopter from './svgs/Helicopter';
import TrafficLights from './svgs/TrafficLights';
import Siren from './svgs/Siren';
import Road from './svgs/Road';
import Engine from './svgs/Engine';
import OilPressure from './svgs/OilPressure';
import CoolantTemperature from './svgs/CoolantTemperature';
import CarBattery from './svgs/CarBattery';
import Gas from './svgs/Gas';
import Gallon from './svgs/Gallon';
import Transmission from './svgs/Transmission';
import Car from './svgs/Car';
import CarWash from './svgs/CarWash';
import CarWash2 from './svgs/CarWash2';
import Bus from './svgs/Bus';
import Bus2 from './svgs/Bus2';
import Car2 from './svgs/Car2';
import Parking from './svgs/Parking';
import CarLock from './svgs/CarLock';
import Taxi from './svgs/Taxi';
import CarSiren from './svgs/CarSiren';
import CarWash3 from './svgs/CarWash3';
import CarWash4 from './svgs/CarWash4';
import Ambulance from './svgs/Ambulance';
import Truck from './svgs/Truck';
import Trailer from './svgs/Trailer';
import ScaleTruck from './svgs/ScaleTruck';
import Train from './svgs/Train';
import Ship from './svgs/Ship';
import Ship2 from './svgs/Ship2';
import Anchor from './svgs/Anchor';
import Boat from './svgs/Boat';
import Bicycle from './svgs/Bicycle';
import Bicycle2 from './svgs/Bicycle2';
import Dumbbell from './svgs/Dumbbell';
import BenchPress from './svgs/BenchPress';
import Swim from './svgs/Swim';
import Football from './svgs/Football';
import BaseballBat from './svgs/BaseballBat';
import Baseball from './svgs/Baseball';
import Tennis from './svgs/Tennis';
import Tennis2 from './svgs/Tennis2';
import PingPong from './svgs/PingPong';
import Hockey from './svgs/Hockey';
import EightBall from './svgs/EightBall';
import Bowling from './svgs/Bowling';
import BowlingPins from './svgs/BowlingPins';
import Golf from './svgs/Golf';
import Golf2 from './svgs/Golf2';
import Archery from './svgs/Archery';
import Slingshot from './svgs/Slingshot';
import Soccer from './svgs/Soccer';
import Basketball from './svgs/Basketball';
import Cube from './svgs/Cube';
import ThreeDRotate from './svgs/ThreeDRotate';
import Puzzle from './svgs/Puzzle';
import Glasses from './svgs/Glasses';
import Glasses2 from './svgs/Glasses2';
import Accessibility from './svgs/Accessibility';
import Wheelchair from './svgs/Wheelchair';
import Wall from './svgs/Wall';
import Fence from './svgs/Fence';
import Wall2 from './svgs/Wall2';
import Icons from './svgs/Icons';
import ResizeHandle from './svgs/ResizeHandle';
import Icons2 from './svgs/Icons2';
import Select from './svgs/Select';
import Select2 from './svgs/Select2';
import SiteMap from './svgs/SiteMap';
import Earth from './svgs/Earth';
import EarthLock from './svgs/EarthLock';
import Network from './svgs/Network';
import NetworkLock from './svgs/NetworkLock';
import Planet from './svgs/Planet';
import Happy from './svgs/Happy';
import Smile from './svgs/Smile';
import Grin from './svgs/Grin';
import Tongue from './svgs/Tongue';
import Sad from './svgs/Sad';
import Wink from './svgs/Wink';
import Dream from './svgs/Dream';
import Shocked from './svgs/Shocked';
import Shocked2 from './svgs/Shocked2';
import Tongue2 from './svgs/Tongue2';
import Neutral from './svgs/Neutral';
import HappyGrin from './svgs/HappyGrin';
import Cool from './svgs/Cool';
import Mad from './svgs/Mad';
import GrinEvil from './svgs/GrinEvil';
import Evil from './svgs/Evil';
import Wow from './svgs/Wow';
import Annoyed from './svgs/Annoyed';
import Wondering from './svgs/Wondering';
import Confused from './svgs/Confused';
import Zipped from './svgs/Zipped';
import Grumpy from './svgs/Grumpy';
import Mustache from './svgs/Mustache';
import TombstoneHipster from './svgs/TombstoneHipster';
import Tombstone from './svgs/Tombstone';
import Ghost from './svgs/Ghost';
import GhostHipster from './svgs/GhostHipster';
import Halloween from './svgs/Halloween';
import Christmas from './svgs/Christmas';
import EasterEgg from './svgs/EasterEgg';
import Mustache2 from './svgs/Mustache2';
import MustacheGlasses from './svgs/MustacheGlasses';
import Pipe from './svgs/Pipe';
import Alarm from './svgs/Alarm';
import AlarmAdd from './svgs/AlarmAdd';
import AlarmSnooze from './svgs/AlarmSnooze';
import AlarmRinging from './svgs/AlarmRinging';
import Bullhorn from './svgs/Bullhorn';
import Hearing from './svgs/Hearing';
import VolumeHigh from './svgs/VolumeHigh';
import VolumeMedium from './svgs/VolumeMedium';
import VolumeLow from './svgs/VolumeLow';
import Volume from './svgs/Volume';
import Mute from './svgs/Mute';
import Lan from './svgs/Lan';
import Lan2 from './svgs/Lan2';
import Wifi from './svgs/Wifi';
import WifiLock from './svgs/WifiLock';
import WifiBlocked from './svgs/WifiBlocked';
import WifiMid from './svgs/WifiMid';
import WifiLow from './svgs/WifiLow';
import WifiLow2 from './svgs/WifiLow2';
import WifiAlert from './svgs/WifiAlert';
import WifiAlertMid from './svgs/WifiAlertMid';
import WifiAlertLow from './svgs/WifiAlertLow';
import WifiAlertLow2 from './svgs/WifiAlertLow2';
import Stream from './svgs/Stream';
import StreamCheck from './svgs/StreamCheck';
import StreamError from './svgs/StreamError';
import StreamAlert from './svgs/StreamAlert';
import Communication from './svgs/Communication';
import CommunicationCrossed from './svgs/CommunicationCrossed';
import Broadcast from './svgs/Broadcast';
import Antenna from './svgs/Antenna';
import Satellite from './svgs/Satellite';
import Satellite2 from './svgs/Satellite2';
import Mic from './svgs/Mic';
import MicMute from './svgs/MicMute';
import Mic2 from './svgs/Mic2';
import Spotlights from './svgs/Spotlights';
import Hourglass from './svgs/Hourglass';
import Loading from './svgs/Loading';
import Loading2 from './svgs/Loading2';
import Loading3 from './svgs/Loading3';
import Refresh from './svgs/Refresh';
import Refresh2 from './svgs/Refresh2';
import Undo from './svgs/Undo';
import Redo from './svgs/Redo';
import Jump2 from './svgs/Jump2';
import Undo2 from './svgs/Undo2';
import Redo2 from './svgs/Redo2';
import Sync from './svgs/Sync';
import RepeatOne2 from './svgs/RepeatOne2';
import SyncCrossed from './svgs/SyncCrossed';
import Sync2 from './svgs/Sync2';
import RepeatOne3 from './svgs/RepeatOne3';
import SyncCrossed2 from './svgs/SyncCrossed2';
import Return from './svgs/Return';
import Return2 from './svgs/Return2';
import Refund from './svgs/Refund';
import History from './svgs/History';
import History2 from './svgs/History2';
import SelfTimer from './svgs/SelfTimer';
import Clock from './svgs/Clock';
import Clock2 from './svgs/Clock2';
import Clock3 from './svgs/Clock3';
import Watch from './svgs/Watch';
import Alarm2 from './svgs/Alarm2';
import AlarmAdd2 from './svgs/AlarmAdd2';
import AlarmRemove from './svgs/AlarmRemove';
import AlarmCheck from './svgs/AlarmCheck';
import AlarmError from './svgs/AlarmError';
import Timer from './svgs/Timer';
import TimerCrossed from './svgs/TimerCrossed';
import Timer2 from './svgs/Timer2';
import TimerCrossed2 from './svgs/TimerCrossed2';
import Download from './svgs/Download';
import Upload from './svgs/Upload';
import Download2 from './svgs/Download2';
import Upload2 from './svgs/Upload2';
import EnterUp from './svgs/EnterUp';
import EnterDown from './svgs/EnterDown';
import EnterLeft from './svgs/EnterLeft';
import EnterRight from './svgs/EnterRight';
import ExitUp from './svgs/ExitUp';
import ExitDown from './svgs/ExitDown';
import ExitLeft from './svgs/ExitLeft';
import ExitRight from './svgs/ExitRight';
import EnterUp2 from './svgs/EnterUp2';
import EnterDown2 from './svgs/EnterDown2';
import EnterVertical from './svgs/EnterVertical';
import EnterLeft2 from './svgs/EnterLeft2';
import EnterRight2 from './svgs/EnterRight2';
import EnterHorizontal from './svgs/EnterHorizontal';
import ExitUp2 from './svgs/ExitUp2';
import ExitDown2 from './svgs/ExitDown2';
import ExitLeft2 from './svgs/ExitLeft2';
import ExitRight2 from './svgs/ExitRight2';
import Cli from './svgs/Cli';
import Bug from './svgs/Bug';
import Code from './svgs/Code';
import FileCode from './svgs/FileCode';
import FileImage from './svgs/FileImage';
import FileZip from './svgs/FileZip';
import FileAudio from './svgs/FileAudio';
import FileVideo from './svgs/FileVideo';
import FilePreview from './svgs/FilePreview';
import FileCharts from './svgs/FileCharts';
import FileStats from './svgs/FileStats';
import FileSpreadsheet from './svgs/FileSpreadsheet';
import Link from './svgs/Link';
import Unlink from './svgs/Unlink';
import Link2 from './svgs/Link2';
import Unlink2 from './svgs/Unlink2';
import ThumbsUp from './svgs/ThumbsUp';
import ThumbsDown from './svgs/ThumbsDown';
import ThumbsUp2 from './svgs/ThumbsUp2';
import ThumbsDown2 from './svgs/ThumbsDown2';
import ThumbsUp3 from './svgs/ThumbsUp3';
import ThumbsDown3 from './svgs/ThumbsDown3';
import Share from './svgs/Share';
import Share2 from './svgs/Share2';
import Share3 from './svgs/Share3';
import Magnifier from './svgs/Magnifier';
import FileSearch from './svgs/FileSearch';
import FindReplace from './svgs/FindReplace';
import ZoomIn from './svgs/ZoomIn';
import ZoomOut from './svgs/ZoomOut';
import Loupe from './svgs/Loupe';
import LoupeZoomIn from './svgs/LoupeZoomIn';
import LoupeZoomOut from './svgs/LoupeZoomOut';
import Cross from './svgs/Cross';
import Menu from './svgs/Menu';
import List from './svgs/List';
import List2 from './svgs/List2';
import List3 from './svgs/List3';
import Menu2 from './svgs/Menu2';
import List4 from './svgs/List4';
import Menu3 from './svgs/Menu3';
import Exclamation from './svgs/Exclamation';
import Question from './svgs/Question';
import Check from './svgs/Check';
import Cross2 from './svgs/Cross2';
import Plus from './svgs/Plus';
import Minus from './svgs/Minus';
import Percent from './svgs/Percent';
import ChevronUp from './svgs/ChevronUp';
import ChevronDown from './svgs/ChevronDown';
import ChevronLeft from './svgs/ChevronLeft';
import ChevronRight from './svgs/ChevronRight';
import ChevronsExpandVertical from './svgs/ChevronsExpandVertical';
import ChevronsExpandHorizontal from './svgs/ChevronsExpandHorizontal';
import ChevronsContractVertical from './svgs/ChevronsContractVertical';
import ChevronsContractHorizontal from './svgs/ChevronsContractHorizontal';
import ArrowUp from './svgs/ArrowUp';
import ArrowDown from './svgs/ArrowDown';
import ArrowLeft from './svgs/ArrowLeft';
import ArrowRight from './svgs/ArrowRight';
import ArrowUpRight from './svgs/ArrowUpRight';
import ArrowsMerge from './svgs/ArrowsMerge';
import ArrowsSplit from './svgs/ArrowsSplit';
import ArrowDivert from './svgs/ArrowDivert';
import ArrowReturn from './svgs/ArrowReturn';
import Expand from './svgs/Expand';
import Contract from './svgs/Contract';
import Expand2 from './svgs/Expand2';
import Contract2 from './svgs/Contract2';
import Move from './svgs/Move';
import Tab from './svgs/Tab';
import ArrowWave from './svgs/ArrowWave';
import Expand3 from './svgs/Expand3';
import Expand4 from './svgs/Expand4';
import Contract3 from './svgs/Contract3';
import Notification from './svgs/Notification';
import Warning from './svgs/Warning';
import NotificationCircle from './svgs/NotificationCircle';
import QuestionCircle from './svgs/QuestionCircle';
import MenuCircle from './svgs/MenuCircle';
import CheckmarkCircle from './svgs/CheckmarkCircle';
import CrossCircle from './svgs/CrossCircle';
import PlusCircle from './svgs/PlusCircle';
import CircleMinus from './svgs/CircleMinus';
import PercentCircle from './svgs/PercentCircle';
import ArrowUpCircle from './svgs/ArrowUpCircle';
import ArrowDownCircle from './svgs/ArrowDownCircle';
import ArrowLeftCircle from './svgs/ArrowLeftCircle';
import ArrowRightCircle from './svgs/ArrowRightCircle';
import ChevronUpCircle from './svgs/ChevronUpCircle';
import ChevronDownCircle from './svgs/ChevronDownCircle';
import ChevronLeftCircle from './svgs/ChevronLeftCircle';
import ChevronRightCircle from './svgs/ChevronRightCircle';
import BackwardCircle from './svgs/BackwardCircle';
import FirstCircle from './svgs/FirstCircle';
import PreviousCircle from './svgs/PreviousCircle';
import StopCircle from './svgs/StopCircle';
import PlayCircle from './svgs/PlayCircle';
import PauseCircle from './svgs/PauseCircle';
import NextCircle from './svgs/NextCircle';
import LastCircle from './svgs/LastCircle';
import ForwardCircle from './svgs/ForwardCircle';
import EjectCircle from './svgs/EjectCircle';
import Crop from './svgs/Crop';
import FrameExpand from './svgs/FrameExpand';
import FrameContract from './svgs/FrameContract';
import Focus from './svgs/Focus';
import Transform from './svgs/Transform';
import Grid from './svgs/Grid';
import GridCrossed from './svgs/GridCrossed';
import Layers from './svgs/Layers';
import LayersCrossed from './svgs/LayersCrossed';
import Toggle from './svgs/Toggle';
import Rulers from './svgs/Rulers';
import Ruler from './svgs/Ruler';
import Funnel from './svgs/Funnel';
import FlipHorizontal from './svgs/FlipHorizontal';
import FlipVertical from './svgs/FlipVertical';
import FlipHorizontal2 from './svgs/FlipHorizontal2';
import FlipVertical2 from './svgs/FlipVertical2';
import Angle from './svgs/Angle';
import Angle2 from './svgs/Angle2';
import Subtract from './svgs/Subtract';
import Combine from './svgs/Combine';
import Intersect from './svgs/Intersect';
import Exclude from './svgs/Exclude';
import AlignCenterVertical from './svgs/AlignCenterVertical';
import AlignRight from './svgs/AlignRight';
import AlignBottom from './svgs/AlignBottom';
import AlignLeft from './svgs/AlignLeft';
import AlignCenterHorizontal from './svgs/AlignCenterHorizontal';
import AlignTop from './svgs/AlignTop';
import Square from './svgs/Square';
import PlusSquare from './svgs/PlusSquare';
import MinusSquare from './svgs/MinusSquare';
import PercentSquare from './svgs/PercentSquare';
import ArrowUpSquare from './svgs/ArrowUpSquare';
import ArrowDownSquare from './svgs/ArrowDownSquare';
import ArrowLeftSquare from './svgs/ArrowLeftSquare';
import ArrowRightSquare from './svgs/ArrowRightSquare';
import ChevronUpSquare from './svgs/ChevronUpSquare';
import ChevronDownSquare from './svgs/ChevronDownSquare';
import ChevronLeftSquare from './svgs/ChevronLeftSquare';
import ChevronRightSquare from './svgs/ChevronRightSquare';
import CheckSquare from './svgs/CheckSquare';
import CrossSquare from './svgs/CrossSquare';
import MenuSquare from './svgs/MenuSquare';
import Prohibited from './svgs/Prohibited';
import Circle from './svgs/Circle';
import RadioButton from './svgs/RadioButton';
import Ligature from './svgs/Ligature';
import TextFormat from './svgs/TextFormat';
import TextFormatRemove from './svgs/TextFormatRemove';
import TextSize from './svgs/TextSize';
import Bold from './svgs/Bold';
import Italic from './svgs/Italic';
import Underline from './svgs/Underline';
import Strikethrough from './svgs/Strikethrough';
import Highlight from './svgs/Highlight';
import TextAlignLeft from './svgs/TextAlignLeft';
import TextAlignCenter from './svgs/TextAlignCenter';
import TextAlignRight from './svgs/TextAlignRight';
import TextAlignJustify from './svgs/TextAlignJustify';
import LineSpacing from './svgs/LineSpacing';
import IndentIncrease from './svgs/IndentIncrease';
import IndentDecrease from './svgs/IndentDecrease';
import TextWrap from './svgs/TextWrap';
import Pilcrow from './svgs/Pilcrow';
import DirectionLtr from './svgs/DirectionLtr';
import DirectionRtl from './svgs/DirectionRtl';
import PageBreak from './svgs/PageBreak';
import PageBreak2 from './svgs/PageBreak2';
import SortAlphaAsc from './svgs/SortAlphaAsc';
import SortAlphaDesc from './svgs/SortAlphaDesc';
import SortNumericAsc from './svgs/SortNumericAsc';
import SortNumericDesc from './svgs/SortNumericDesc';
import SortAmountAsc from './svgs/SortAmountAsc';
import SortAmountDesc from './svgs/SortAmountDesc';
import SortTimeAsc from './svgs/SortTimeAsc';
import SortTimeDesc from './svgs/SortTimeDesc';
import Sigma from './svgs/Sigma';
import PencilLine from './svgs/PencilLine';
import Hand from './svgs/Hand';
import PointerUp from './svgs/PointerUp';
import PointerRight from './svgs/PointerRight';
import PointerDown from './svgs/PointerDown';
import PointerLeft from './svgs/PointerLeft';
import FingerTap from './svgs/FingerTap';
import FingersTap from './svgs/FingersTap';
import Reminder from './svgs/Reminder';
import FingersCrossed from './svgs/FingersCrossed';
import FingersVictory from './svgs/FingersVictory';
import GestureZoom from './svgs/GestureZoom';
import GesturePinch from './svgs/GesturePinch';
import FingersScrollHorizontal from './svgs/FingersScrollHorizontal';
import FingersScrollVertical from './svgs/FingersScrollVertical';
import FingersScrollLeft from './svgs/FingersScrollLeft';
import FingersScrollRight from './svgs/FingersScrollRight';
import Hand2 from './svgs/Hand2';
import PointerUp2 from './svgs/PointerUp2';
import PointerRight2 from './svgs/PointerRight2';
import PointerDown2 from './svgs/PointerDown2';
import PointerLeft2 from './svgs/PointerLeft2';
import FingerTap2 from './svgs/FingerTap2';
import FingersTap2 from './svgs/FingersTap2';
import Reminder2 from './svgs/Reminder2';
import GestureZoom2 from './svgs/GestureZoom2';
import GesturePinch2 from './svgs/GesturePinch2';
import FingersScrollHorizontal2 from './svgs/FingersScrollHorizontal2';
import FingersScrollVertical2 from './svgs/FingersScrollVertical2';
import FingersScrollLeft2 from './svgs/FingersScrollLeft2';
import FingersScrollRight2 from './svgs/FingersScrollRight2';
import FingersScrollVertical3 from './svgs/FingersScrollVertical3';
import BorderStyle from './svgs/BorderStyle';
import BorderAll from './svgs/BorderAll';
import BorderOuter from './svgs/BorderOuter';
import BorderInner from './svgs/BorderInner';
import BorderTop from './svgs/BorderTop';
import BorderHorizontal from './svgs/BorderHorizontal';
import BorderBottom from './svgs/BorderBottom';
import BorderLeft from './svgs/BorderLeft';
import BorderVertical from './svgs/BorderVertical';
import BorderRight from './svgs/BorderRight';
import BorderNone from './svgs/BorderNone';
import Ellipsis from './svgs/Ellipsis';

const icons = {
    Home,
    Home2,
    Home3,
    Home4,
    Home5,
    Home6,
    Bathtub,
    Toothbrush,
    Bed,
    Couch,
    Chair,
    City,
    Apartment,
    Pencil,
    Pencil2,
    Pen,
    Pencil3,
    Eraser,
    Pencil4,
    Pencil5,
    Feather,
    Feather2,
    Feather3,
    Pen2,
    PenAdd,
    PenRemove,
    Vector,
    Pen3,
    Blog,
    Brush,
    Brush2,
    Spray,
    PaintRoller,
    Stamp,
    Tape,
    DeskTape,
    Texture,
    EyeDropper,
    Palette,
    ColorSampler,
    Bucket,
    Gradient,
    Gradient2,
    MagicWand,
    Magnet,
    PencilRuler,
    PencilRuler2,
    Compass,
    Aim,
    Gun,
    Bottle,
    Drop,
    DropCrossed,
    Drop2,
    Snow,
    Snow2,
    Fire,
    Lighter,
    Knife,
    Dagger,
    Tissue,
    ToiletPaper,
    Poop,
    Umbrella,
    Umbrella2,
    Rain,
    Tornado,
    Wind,
    Fan,
    Contrast,
    SunSmall,
    Sun,
    Sun2,
    Moon,
    Cloud,
    CloudUpload,
    CloudDownload,
    CloudRain,
    CloudHailstones,
    CloudSnow,
    CloudWindy,
    SunWind,
    CloudFog,
    CloudSun,
    CloudLightning,
    CloudSync,
    CloudLock,
    CloudGear,
    CloudAlert,
    CloudCheck,
    CloudCross,
    CloudCrossed,
    CloudDatabase,
    Database,
    DatabaseAdd,
    DatabaseRemove,
    DatabaseLock,
    DatabaseRefresh,
    DatabaseCheck,
    DatabaseHistory,
    DatabaseUpload,
    DatabaseDownload,
    Server,
    Shield,
    ShieldCheck,
    ShieldAlert,
    ShieldCross,
    Lock,
    RotationLock,
    Unlock,
    Key,
    KeyHole,
    ToggleOff,
    ToggleOn,
    Cog,
    Cog2,
    Wrench,
    Screwdriver,
    HammerWrench,
    Hammer,
    Saw,
    Axe,
    Axe2,
    Shovel,
    Pickaxe,
    Factory,
    Factory2,
    Recycle,
    Trash,
    Trash2,
    Trash3,
    Broom,
    Game,
    Gamepad,
    Joystick,
    Dice,
    Spades,
    Diamonds,
    Clubs,
    Hearts,
    Heart,
    Star,
    StarHalf,
    StarEmpty,
    Flag,
    Flag2,
    Flag3,
    MailboxFull,
    MailboxEmpty,
    AtSign,
    Envelope,
    EnvelopeOpen,
    Paperclip,
    PaperPlane,
    Reply,
    ReplyAll,
    Inbox,
    Inbox2,
    Outbox,
    Box,
    Archive,
    Archive2,
    Drawers,
    Drawers2,
    Drawers3,
    Eye,
    EyeCrossed,
    EyePlus,
    EyeMinus,
    Binoculars,
    Binoculars2,
    Hdd,
    HddDown,
    HddUp,
    FloppyDisk,
    Disc,
    Tape2,
    Printer,
    Shredder,
    FileEmpty,
    FileAdd,
    FileCheck,
    FileLock,
    Files,
    Copy,
    Compare,
    Folder,
    FolderSearch,
    FolderPlus,
    FolderMinus,
    FolderDownload,
    FolderUpload,
    FolderStar,
    FolderHeart,
    FolderUser,
    FolderShared,
    FolderMusic,
    FolderPicture,
    FolderFilm,
    Scissors,
    Paste,
    ClipboardEmpty,
    ClipboardPencil,
    ClipboardText,
    ClipboardCheck,
    ClipboardDown,
    ClipboardLeft,
    ClipboardAlert,
    ClipboardUser,
    Register,
    Enter,
    Exit,
    Papers,
    News,
    Reading,
    Typewriter,
    Document,
    Document2,
    GraduationHat,
    License,
    License2,
    MedalEmpty,
    MedalFirst,
    MedalSecond,
    MedalThird,
    Podium,
    Trophy,
    Trophy2,
    MusicNote,
    MusicNote2,
    MusicNote3,
    Playlist,
    PlaylistAdd,
    Guitar,
    Trumpet,
    Album,
    Shuffle,
    RepeatOne,
    Repeat,
    Headphones,
    Headset,
    Loudspeaker,
    Equalizer,
    Theater,
    ThreeDGlasses,
    Ticket,
    Presentation,
    Play,
    FilmPlay,
    ClapboardPlay,
    Media,
    Film,
    Film2,
    Surveillance,
    Surveillance2,
    Camera,
    CameraCrossed,
    CameraPlay,
    TimeLapse,
    Record,
    Camera2,
    CameraFlip,
    Panorama,
    TimeLapse2,
    Shutter,
    Shutter2,
    FaceDetection,
    Flare,
    Convex,
    Concave,
    Picture,
    Picture2,
    Picture3,
    Pictures,
    Book,
    AudioBook,
    Book2,
    Bookmark,
    Bookmark2,
    Label,
    Library,
    Library2,
    Contacts,
    Profile,
    Portrait,
    Portrait2,
    User,
    UserPlus,
    UserMinus,
    UserLock,
    Users,
    Users2,
    UsersPlus,
    UsersMinus,
    GroupWork,
    Woman,
    Man,
    Baby,
    Baby2,
    Baby3,
    BabyBottle,
    Walk,
    HandWaving,
    Jump,
    Run,
    Woman2,
    Man2,
    ManWoman,
    Height,
    Weight,
    Scale,
    Button,
    BowTie,
    Tie,
    Socks,
    Shoe,
    Shoes,
    Hat,
    Pants,
    Shorts,
    FlipFlops,
    Shirt,
    Hanger,
    Laundry,
    Store,
    Haircut,
    Store24,
    Barcode,
    Barcode2,
    Barcode3,
    Cashier,
    Bag,
    Bag2,
    Cart,
    CartEmpty,
    CartFull,
    CartPlus,
    CartPlus2,
    CartAdd,
    CartRemove,
    CartExchange,
    Tag,
    Tags,
    Receipt,
    Wallet,
    CreditCard,
    CashDollar,
    CashEuro,
    CashPound,
    CashYen,
    BagDollar,
    BagEuro,
    BagPound,
    BagYen,
    CoinDollar,
    CoinEuro,
    CoinPound,
    CoinYen,
    Calculator,
    Calculator2,
    Abacus,
    Vault,
    Telephone,
    PhoneLock,
    PhoneWave,
    PhonePause,
    PhoneOutgoing,
    PhoneIncoming,
    PhoneInOut,
    PhoneError,
    PhoneSip,
    PhonePlus,
    PhoneMinus,
    Voicemail,
    Dial,
    Telephone2,
    Pushpin,
    Pushpin2,
    MapMarker,
    MapMarkerUser,
    MapMarkerDown,
    MapMarkerCheck,
    MapMarkerCrossed,
    Radar,
    Compass2,
    Map,
    Map2,
    Location,
    RoadSign,
    CalendarEmpty,
    CalendarCheck,
    CalendarCross,
    Calendar31,
    CalendarFull,
    CalendarInsert,
    CalendarText,
    CalendarUser,
    Mouse,
    MouseLeft,
    MouseRight,
    MouseBoth,
    Keyboard,
    KeyboardUp,
    KeyboardDown,
    Delete,
    SpellCheck,
    Escape,
    Enter2,
    Screen,
    AspectRatio,
    Signal,
    SignalLock,
    Signal80,
    Signal60,
    Signal40,
    Signal20,
    Signal0,
    SignalBlocked,
    Sim,
    FlashMemory,
    UsbDrive,
    Phone,
    Smartphone,
    SmartphoneNotification,
    SmartphoneVibration,
    SmartphoneEmbed,
    SmartphoneWaves,
    Tablet,
    Tablet2,
    Laptop,
    LaptopPhone,
    Desktop,
    Launch,
    NewTab,
    Window,
    Cable,
    Cable2,
    Tv,
    Radio,
    RemoteControl,
    PowerSwitch,
    Power,
    PowerCrossed,
    FlashAuto,
    Lamp,
    Flashlight,
    Lampshade,
    Cord,
    Outlet,
    BatteryPower,
    BatteryEmpty,
    BatteryAlert,
    BatteryError,
    BatteryLow1,
    BatteryLow2,
    BatteryLow3,
    BatteryMid1,
    BatteryMid2,
    BatteryMid3,
    BatteryFull,
    BatteryCharging,
    BatteryCharging2,
    BatteryCharging3,
    BatteryCharging4,
    BatteryCharging5,
    BatteryCharging6,
    BatteryCharging7,
    Chip,
    ChipX64,
    ChipX86,
    Bubble,
    Bubbles,
    BubbleDots,
    BubbleAlert,
    BubbleQuestion,
    BubbleText,
    BubblePencil,
    BubblePicture,
    BubbleVideo,
    BubbleUser,
    BubbleQuote,
    BubbleHeart,
    BubbleEmoticon,
    BubbleAttachment,
    PhoneBubble,
    QuoteOpen,
    QuoteClose,
    Dna,
    HeartPulse,
    Pulse,
    Syringe,
    Pills,
    FirstAid,
    Lifebuoy,
    Bandage,
    Bandages,
    Thermometer,
    Microscope,
    Brain,
    Beaker,
    Skull,
    Bone,
    Construction,
    ConstructionCone,
    PieChart,
    PieChart2,
    Graph,
    ChartGrowth,
    ChartBars,
    ChartSettings,
    Cake,
    Gift,
    Balloon,
    Rank,
    Rank2,
    Rank3,
    Crown,
    Lotus,
    Diamond,
    Diamond2,
    Diamond3,
    Diamond4,
    Linearicons,
    Teacup,
    Teapot,
    Glass,
    Bottle2,
    GlassCocktail,
    Glass2,
    Dinner,
    Dinner2,
    Chef,
    Scale2,
    Egg,
    Egg2,
    Eggs,
    Platter,
    Steak,
    Hamburger,
    Hotdog,
    Pizza,
    Sausage,
    Chicken,
    Fish,
    Carrot,
    Cheese,
    Bread,
    IceCream,
    IceCream2,
    Candy,
    Lollipop,
    CoffeeBean,
    CoffeeCup,
    Cherry,
    Grapes,
    Citrus,
    Apple,
    Leaf,
    Landscape,
    PineTree,
    Tree,
    Cactus,
    Paw,
    Footprint,
    SpeedSlow,
    SpeedMedium,
    SpeedFast,
    Rocket,
    Hammer2,
    Balance,
    Briefcase,
    LuggageWeight,
    Dolly,
    Plane,
    PlaneCrossed,
    Helicopter,
    TrafficLights,
    Siren,
    Road,
    Engine,
    OilPressure,
    CoolantTemperature,
    CarBattery,
    Gas,
    Gallon,
    Transmission,
    Car,
    CarWash,
    CarWash2,
    Bus,
    Bus2,
    Car2,
    Parking,
    CarLock,
    Taxi,
    CarSiren,
    CarWash3,
    CarWash4,
    Ambulance,
    Truck,
    Trailer,
    ScaleTruck,
    Train,
    Ship,
    Ship2,
    Anchor,
    Boat,
    Bicycle,
    Bicycle2,
    Dumbbell,
    BenchPress,
    Swim,
    Football,
    BaseballBat,
    Baseball,
    Tennis,
    Tennis2,
    PingPong,
    Hockey,
    EightBall,
    Bowling,
    BowlingPins,
    Golf,
    Golf2,
    Archery,
    Slingshot,
    Soccer,
    Basketball,
    Cube,
    ThreeDRotate,
    Puzzle,
    Glasses,
    Glasses2,
    Accessibility,
    Wheelchair,
    Wall,
    Fence,
    Wall2,
    Icons,
    ResizeHandle,
    Icons2,
    Select,
    Select2,
    SiteMap,
    Earth,
    EarthLock,
    Network,
    NetworkLock,
    Planet,
    Happy,
    Smile,
    Grin,
    Tongue,
    Sad,
    Wink,
    Dream,
    Shocked,
    Shocked2,
    Tongue2,
    Neutral,
    HappyGrin,
    Cool,
    Mad,
    GrinEvil,
    Evil,
    Wow,
    Annoyed,
    Wondering,
    Confused,
    Zipped,
    Grumpy,
    Mustache,
    TombstoneHipster,
    Tombstone,
    Ghost,
    GhostHipster,
    Halloween,
    Christmas,
    EasterEgg,
    Mustache2,
    MustacheGlasses,
    Pipe,
    Alarm,
    AlarmAdd,
    AlarmSnooze,
    AlarmRinging,
    Bullhorn,
    Hearing,
    VolumeHigh,
    VolumeMedium,
    VolumeLow,
    Volume,
    Mute,
    Lan,
    Lan2,
    Wifi,
    WifiLock,
    WifiBlocked,
    WifiMid,
    WifiLow,
    WifiLow2,
    WifiAlert,
    WifiAlertMid,
    WifiAlertLow,
    WifiAlertLow2,
    Stream,
    StreamCheck,
    StreamError,
    StreamAlert,
    Communication,
    CommunicationCrossed,
    Broadcast,
    Antenna,
    Satellite,
    Satellite2,
    Mic,
    MicMute,
    Mic2,
    Spotlights,
    Hourglass,
    Loading,
    Loading2,
    Loading3,
    Refresh,
    Refresh2,
    Undo,
    Redo,
    Jump2,
    Undo2,
    Redo2,
    Sync,
    RepeatOne2,
    SyncCrossed,
    Sync2,
    RepeatOne3,
    SyncCrossed2,
    Return,
    Return2,
    Refund,
    History,
    History2,
    SelfTimer,
    Clock,
    Clock2,
    Clock3,
    Watch,
    Alarm2,
    AlarmAdd2,
    AlarmRemove,
    AlarmCheck,
    AlarmError,
    Timer,
    TimerCrossed,
    Timer2,
    TimerCrossed2,
    Download,
    Upload,
    Download2,
    Upload2,
    EnterUp,
    EnterDown,
    EnterLeft,
    EnterRight,
    ExitUp,
    ExitDown,
    ExitLeft,
    ExitRight,
    EnterUp2,
    EnterDown2,
    EnterVertical,
    EnterLeft2,
    EnterRight2,
    EnterHorizontal,
    ExitUp2,
    ExitDown2,
    ExitLeft2,
    ExitRight2,
    Cli,
    Bug,
    Code,
    FileCode,
    FileImage,
    FileZip,
    FileAudio,
    FileVideo,
    FilePreview,
    FileCharts,
    FileStats,
    FileSpreadsheet,
    Link,
    Unlink,
    Link2,
    Unlink2,
    ThumbsUp,
    ThumbsDown,
    ThumbsUp2,
    ThumbsDown2,
    ThumbsUp3,
    ThumbsDown3,
    Share,
    Share2,
    Share3,
    Magnifier,
    FileSearch,
    FindReplace,
    ZoomIn,
    ZoomOut,
    Loupe,
    LoupeZoomIn,
    LoupeZoomOut,
    Cross,
    Menu,
    List,
    List2,
    List3,
    Menu2,
    List4,
    Menu3,
    Exclamation,
    Question,
    Check,
    Cross2,
    Plus,
    Minus,
    Percent,
    ChevronUp,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsExpandVertical,
    ChevronsExpandHorizontal,
    ChevronsContractVertical,
    ChevronsContractHorizontal,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUpRight,
    ArrowsMerge,
    ArrowsSplit,
    ArrowDivert,
    ArrowReturn,
    Expand,
    Contract,
    Expand2,
    Contract2,
    Move,
    Tab,
    ArrowWave,
    Expand3,
    Expand4,
    Contract3,
    Notification,
    Warning,
    NotificationCircle,
    QuestionCircle,
    MenuCircle,
    CheckmarkCircle,
    CrossCircle,
    PlusCircle,
    CircleMinus,
    PercentCircle,
    ArrowUpCircle,
    ArrowDownCircle,
    ArrowLeftCircle,
    ArrowRightCircle,
    ChevronUpCircle,
    ChevronDownCircle,
    ChevronLeftCircle,
    ChevronRightCircle,
    BackwardCircle,
    FirstCircle,
    PreviousCircle,
    StopCircle,
    PlayCircle,
    PauseCircle,
    NextCircle,
    LastCircle,
    ForwardCircle,
    EjectCircle,
    Crop,
    FrameExpand,
    FrameContract,
    Focus,
    Transform,
    Grid,
    GridCrossed,
    Layers,
    LayersCrossed,
    Toggle,
    Rulers,
    Ruler,
    Funnel,
    FlipHorizontal,
    FlipVertical,
    FlipHorizontal2,
    FlipVertical2,
    Angle,
    Angle2,
    Subtract,
    Combine,
    Intersect,
    Exclude,
    AlignCenterVertical,
    AlignRight,
    AlignBottom,
    AlignLeft,
    AlignCenterHorizontal,
    AlignTop,
    Square,
    PlusSquare,
    MinusSquare,
    PercentSquare,
    ArrowUpSquare,
    ArrowDownSquare,
    ArrowLeftSquare,
    ArrowRightSquare,
    ChevronUpSquare,
    ChevronDownSquare,
    ChevronLeftSquare,
    ChevronRightSquare,
    CheckSquare,
    CrossSquare,
    MenuSquare,
    Prohibited,
    Circle,
    RadioButton,
    Ligature,
    TextFormat,
    TextFormatRemove,
    TextSize,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Highlight,
    TextAlignLeft,
    TextAlignCenter,
    TextAlignRight,
    TextAlignJustify,
    LineSpacing,
    IndentIncrease,
    IndentDecrease,
    TextWrap,
    Pilcrow,
    DirectionLtr,
    DirectionRtl,
    PageBreak,
    PageBreak2,
    SortAlphaAsc,
    SortAlphaDesc,
    SortNumericAsc,
    SortNumericDesc,
    SortAmountAsc,
    SortAmountDesc,
    SortTimeAsc,
    SortTimeDesc,
    Sigma,
    PencilLine,
    Hand,
    PointerUp,
    PointerRight,
    PointerDown,
    PointerLeft,
    FingerTap,
    FingersTap,
    Reminder,
    FingersCrossed,
    FingersVictory,
    GestureZoom,
    GesturePinch,
    FingersScrollHorizontal,
    FingersScrollVertical,
    FingersScrollLeft,
    FingersScrollRight,
    Hand2,
    PointerUp2,
    PointerRight2,
    PointerDown2,
    PointerLeft2,
    FingerTap2,
    FingersTap2,
    Reminder2,
    GestureZoom2,
    GesturePinch2,
    FingersScrollHorizontal2,
    FingersScrollVertical2,
    FingersScrollLeft2,
    FingersScrollRight2,
    FingersScrollVertical3,
    BorderStyle,
    BorderAll,
    BorderOuter,
    BorderInner,
    BorderTop,
    BorderHorizontal,
    BorderBottom,
    BorderLeft,
    BorderVertical,
    BorderRight,
    BorderNone,
    Ellipsis,
};

export {
    icons as default,
    Home,
    Home2,
    Home3,
    Home4,
    Home5,
    Home6,
    Bathtub,
    Toothbrush,
    Bed,
    Couch,
    Chair,
    City,
    Apartment,
    Pencil,
    Pencil2,
    Pen,
    Pencil3,
    Eraser,
    Pencil4,
    Pencil5,
    Feather,
    Feather2,
    Feather3,
    Pen2,
    PenAdd,
    PenRemove,
    Vector,
    Pen3,
    Blog,
    Brush,
    Brush2,
    Spray,
    PaintRoller,
    Stamp,
    Tape,
    DeskTape,
    Texture,
    EyeDropper,
    Palette,
    ColorSampler,
    Bucket,
    Gradient,
    Gradient2,
    MagicWand,
    Magnet,
    PencilRuler,
    PencilRuler2,
    Compass,
    Aim,
    Gun,
    Bottle,
    Drop,
    DropCrossed,
    Drop2,
    Snow,
    Snow2,
    Fire,
    Lighter,
    Knife,
    Dagger,
    Tissue,
    ToiletPaper,
    Poop,
    Umbrella,
    Umbrella2,
    Rain,
    Tornado,
    Wind,
    Fan,
    Contrast,
    SunSmall,
    Sun,
    Sun2,
    Moon,
    Cloud,
    CloudUpload,
    CloudDownload,
    CloudRain,
    CloudHailstones,
    CloudSnow,
    CloudWindy,
    SunWind,
    CloudFog,
    CloudSun,
    CloudLightning,
    CloudSync,
    CloudLock,
    CloudGear,
    CloudAlert,
    CloudCheck,
    CloudCross,
    CloudCrossed,
    CloudDatabase,
    Database,
    DatabaseAdd,
    DatabaseRemove,
    DatabaseLock,
    DatabaseRefresh,
    DatabaseCheck,
    DatabaseHistory,
    DatabaseUpload,
    DatabaseDownload,
    Server,
    Shield,
    ShieldCheck,
    ShieldAlert,
    ShieldCross,
    Lock,
    RotationLock,
    Unlock,
    Key,
    KeyHole,
    ToggleOff,
    ToggleOn,
    Cog,
    Cog2,
    Wrench,
    Screwdriver,
    HammerWrench,
    Hammer,
    Saw,
    Axe,
    Axe2,
    Shovel,
    Pickaxe,
    Factory,
    Factory2,
    Recycle,
    Trash,
    Trash2,
    Trash3,
    Broom,
    Game,
    Gamepad,
    Joystick,
    Dice,
    Spades,
    Diamonds,
    Clubs,
    Hearts,
    Heart,
    Star,
    StarHalf,
    StarEmpty,
    Flag,
    Flag2,
    Flag3,
    MailboxFull,
    MailboxEmpty,
    AtSign,
    Envelope,
    EnvelopeOpen,
    Paperclip,
    PaperPlane,
    Reply,
    ReplyAll,
    Inbox,
    Inbox2,
    Outbox,
    Box,
    Archive,
    Archive2,
    Drawers,
    Drawers2,
    Drawers3,
    Eye,
    EyeCrossed,
    EyePlus,
    EyeMinus,
    Binoculars,
    Binoculars2,
    Hdd,
    HddDown,
    HddUp,
    FloppyDisk,
    Disc,
    Tape2,
    Printer,
    Shredder,
    FileEmpty,
    FileAdd,
    FileCheck,
    FileLock,
    Files,
    Copy,
    Compare,
    Folder,
    FolderSearch,
    FolderPlus,
    FolderMinus,
    FolderDownload,
    FolderUpload,
    FolderStar,
    FolderHeart,
    FolderUser,
    FolderShared,
    FolderMusic,
    FolderPicture,
    FolderFilm,
    Scissors,
    Paste,
    ClipboardEmpty,
    ClipboardPencil,
    ClipboardText,
    ClipboardCheck,
    ClipboardDown,
    ClipboardLeft,
    ClipboardAlert,
    ClipboardUser,
    Register,
    Enter,
    Exit,
    Papers,
    News,
    Reading,
    Typewriter,
    Document,
    Document2,
    GraduationHat,
    License,
    License2,
    MedalEmpty,
    MedalFirst,
    MedalSecond,
    MedalThird,
    Podium,
    Trophy,
    Trophy2,
    MusicNote,
    MusicNote2,
    MusicNote3,
    Playlist,
    PlaylistAdd,
    Guitar,
    Trumpet,
    Album,
    Shuffle,
    RepeatOne,
    Repeat,
    Headphones,
    Headset,
    Loudspeaker,
    Equalizer,
    Theater,
    ThreeDGlasses,
    Ticket,
    Presentation,
    Play,
    FilmPlay,
    ClapboardPlay,
    Media,
    Film,
    Film2,
    Surveillance,
    Surveillance2,
    Camera,
    CameraCrossed,
    CameraPlay,
    TimeLapse,
    Record,
    Camera2,
    CameraFlip,
    Panorama,
    TimeLapse2,
    Shutter,
    Shutter2,
    FaceDetection,
    Flare,
    Convex,
    Concave,
    Picture,
    Picture2,
    Picture3,
    Pictures,
    Book,
    AudioBook,
    Book2,
    Bookmark,
    Bookmark2,
    Label,
    Library,
    Library2,
    Contacts,
    Profile,
    Portrait,
    Portrait2,
    User,
    UserPlus,
    UserMinus,
    UserLock,
    Users,
    Users2,
    UsersPlus,
    UsersMinus,
    GroupWork,
    Woman,
    Man,
    Baby,
    Baby2,
    Baby3,
    BabyBottle,
    Walk,
    HandWaving,
    Jump,
    Run,
    Woman2,
    Man2,
    ManWoman,
    Height,
    Weight,
    Scale,
    Button,
    BowTie,
    Tie,
    Socks,
    Shoe,
    Shoes,
    Hat,
    Pants,
    Shorts,
    FlipFlops,
    Shirt,
    Hanger,
    Laundry,
    Store,
    Haircut,
    Store24,
    Barcode,
    Barcode2,
    Barcode3,
    Cashier,
    Bag,
    Bag2,
    Cart,
    CartEmpty,
    CartFull,
    CartPlus,
    CartPlus2,
    CartAdd,
    CartRemove,
    CartExchange,
    Tag,
    Tags,
    Receipt,
    Wallet,
    CreditCard,
    CashDollar,
    CashEuro,
    CashPound,
    CashYen,
    BagDollar,
    BagEuro,
    BagPound,
    BagYen,
    CoinDollar,
    CoinEuro,
    CoinPound,
    CoinYen,
    Calculator,
    Calculator2,
    Abacus,
    Vault,
    Telephone,
    PhoneLock,
    PhoneWave,
    PhonePause,
    PhoneOutgoing,
    PhoneIncoming,
    PhoneInOut,
    PhoneError,
    PhoneSip,
    PhonePlus,
    PhoneMinus,
    Voicemail,
    Dial,
    Telephone2,
    Pushpin,
    Pushpin2,
    MapMarker,
    MapMarkerUser,
    MapMarkerDown,
    MapMarkerCheck,
    MapMarkerCrossed,
    Radar,
    Compass2,
    Map,
    Map2,
    Location,
    RoadSign,
    CalendarEmpty,
    CalendarCheck,
    CalendarCross,
    Calendar31,
    CalendarFull,
    CalendarInsert,
    CalendarText,
    CalendarUser,
    Mouse,
    MouseLeft,
    MouseRight,
    MouseBoth,
    Keyboard,
    KeyboardUp,
    KeyboardDown,
    Delete,
    SpellCheck,
    Escape,
    Enter2,
    Screen,
    AspectRatio,
    Signal,
    SignalLock,
    Signal80,
    Signal60,
    Signal40,
    Signal20,
    Signal0,
    SignalBlocked,
    Sim,
    FlashMemory,
    UsbDrive,
    Phone,
    Smartphone,
    SmartphoneNotification,
    SmartphoneVibration,
    SmartphoneEmbed,
    SmartphoneWaves,
    Tablet,
    Tablet2,
    Laptop,
    LaptopPhone,
    Desktop,
    Launch,
    NewTab,
    Window,
    Cable,
    Cable2,
    Tv,
    Radio,
    RemoteControl,
    PowerSwitch,
    Power,
    PowerCrossed,
    FlashAuto,
    Lamp,
    Flashlight,
    Lampshade,
    Cord,
    Outlet,
    BatteryPower,
    BatteryEmpty,
    BatteryAlert,
    BatteryError,
    BatteryLow1,
    BatteryLow2,
    BatteryLow3,
    BatteryMid1,
    BatteryMid2,
    BatteryMid3,
    BatteryFull,
    BatteryCharging,
    BatteryCharging2,
    BatteryCharging3,
    BatteryCharging4,
    BatteryCharging5,
    BatteryCharging6,
    BatteryCharging7,
    Chip,
    ChipX64,
    ChipX86,
    Bubble,
    Bubbles,
    BubbleDots,
    BubbleAlert,
    BubbleQuestion,
    BubbleText,
    BubblePencil,
    BubblePicture,
    BubbleVideo,
    BubbleUser,
    BubbleQuote,
    BubbleHeart,
    BubbleEmoticon,
    BubbleAttachment,
    PhoneBubble,
    QuoteOpen,
    QuoteClose,
    Dna,
    HeartPulse,
    Pulse,
    Syringe,
    Pills,
    FirstAid,
    Lifebuoy,
    Bandage,
    Bandages,
    Thermometer,
    Microscope,
    Brain,
    Beaker,
    Skull,
    Bone,
    Construction,
    ConstructionCone,
    PieChart,
    PieChart2,
    Graph,
    ChartGrowth,
    ChartBars,
    ChartSettings,
    Cake,
    Gift,
    Balloon,
    Rank,
    Rank2,
    Rank3,
    Crown,
    Lotus,
    Diamond,
    Diamond2,
    Diamond3,
    Diamond4,
    Linearicons,
    Teacup,
    Teapot,
    Glass,
    Bottle2,
    GlassCocktail,
    Glass2,
    Dinner,
    Dinner2,
    Chef,
    Scale2,
    Egg,
    Egg2,
    Eggs,
    Platter,
    Steak,
    Hamburger,
    Hotdog,
    Pizza,
    Sausage,
    Chicken,
    Fish,
    Carrot,
    Cheese,
    Bread,
    IceCream,
    IceCream2,
    Candy,
    Lollipop,
    CoffeeBean,
    CoffeeCup,
    Cherry,
    Grapes,
    Citrus,
    Apple,
    Leaf,
    Landscape,
    PineTree,
    Tree,
    Cactus,
    Paw,
    Footprint,
    SpeedSlow,
    SpeedMedium,
    SpeedFast,
    Rocket,
    Hammer2,
    Balance,
    Briefcase,
    LuggageWeight,
    Dolly,
    Plane,
    PlaneCrossed,
    Helicopter,
    TrafficLights,
    Siren,
    Road,
    Engine,
    OilPressure,
    CoolantTemperature,
    CarBattery,
    Gas,
    Gallon,
    Transmission,
    Car,
    CarWash,
    CarWash2,
    Bus,
    Bus2,
    Car2,
    Parking,
    CarLock,
    Taxi,
    CarSiren,
    CarWash3,
    CarWash4,
    Ambulance,
    Truck,
    Trailer,
    ScaleTruck,
    Train,
    Ship,
    Ship2,
    Anchor,
    Boat,
    Bicycle,
    Bicycle2,
    Dumbbell,
    BenchPress,
    Swim,
    Football,
    BaseballBat,
    Baseball,
    Tennis,
    Tennis2,
    PingPong,
    Hockey,
    EightBall,
    Bowling,
    BowlingPins,
    Golf,
    Golf2,
    Archery,
    Slingshot,
    Soccer,
    Basketball,
    Cube,
    ThreeDRotate,
    Puzzle,
    Glasses,
    Glasses2,
    Accessibility,
    Wheelchair,
    Wall,
    Fence,
    Wall2,
    Icons,
    ResizeHandle,
    Icons2,
    Select,
    Select2,
    SiteMap,
    Earth,
    EarthLock,
    Network,
    NetworkLock,
    Planet,
    Happy,
    Smile,
    Grin,
    Tongue,
    Sad,
    Wink,
    Dream,
    Shocked,
    Shocked2,
    Tongue2,
    Neutral,
    HappyGrin,
    Cool,
    Mad,
    GrinEvil,
    Evil,
    Wow,
    Annoyed,
    Wondering,
    Confused,
    Zipped,
    Grumpy,
    Mustache,
    TombstoneHipster,
    Tombstone,
    Ghost,
    GhostHipster,
    Halloween,
    Christmas,
    EasterEgg,
    Mustache2,
    MustacheGlasses,
    Pipe,
    Alarm,
    AlarmAdd,
    AlarmSnooze,
    AlarmRinging,
    Bullhorn,
    Hearing,
    VolumeHigh,
    VolumeMedium,
    VolumeLow,
    Volume,
    Mute,
    Lan,
    Lan2,
    Wifi,
    WifiLock,
    WifiBlocked,
    WifiMid,
    WifiLow,
    WifiLow2,
    WifiAlert,
    WifiAlertMid,
    WifiAlertLow,
    WifiAlertLow2,
    Stream,
    StreamCheck,
    StreamError,
    StreamAlert,
    Communication,
    CommunicationCrossed,
    Broadcast,
    Antenna,
    Satellite,
    Satellite2,
    Mic,
    MicMute,
    Mic2,
    Spotlights,
    Hourglass,
    Loading,
    Loading2,
    Loading3,
    Refresh,
    Refresh2,
    Undo,
    Redo,
    Jump2,
    Undo2,
    Redo2,
    Sync,
    RepeatOne2,
    SyncCrossed,
    Sync2,
    RepeatOne3,
    SyncCrossed2,
    Return,
    Return2,
    Refund,
    History,
    History2,
    SelfTimer,
    Clock,
    Clock2,
    Clock3,
    Watch,
    Alarm2,
    AlarmAdd2,
    AlarmRemove,
    AlarmCheck,
    AlarmError,
    Timer,
    TimerCrossed,
    Timer2,
    TimerCrossed2,
    Download,
    Upload,
    Download2,
    Upload2,
    EnterUp,
    EnterDown,
    EnterLeft,
    EnterRight,
    ExitUp,
    ExitDown,
    ExitLeft,
    ExitRight,
    EnterUp2,
    EnterDown2,
    EnterVertical,
    EnterLeft2,
    EnterRight2,
    EnterHorizontal,
    ExitUp2,
    ExitDown2,
    ExitLeft2,
    ExitRight2,
    Cli,
    Bug,
    Code,
    FileCode,
    FileImage,
    FileZip,
    FileAudio,
    FileVideo,
    FilePreview,
    FileCharts,
    FileStats,
    FileSpreadsheet,
    Link,
    Unlink,
    Link2,
    Unlink2,
    ThumbsUp,
    ThumbsDown,
    ThumbsUp2,
    ThumbsDown2,
    ThumbsUp3,
    ThumbsDown3,
    Share,
    Share2,
    Share3,
    Magnifier,
    FileSearch,
    FindReplace,
    ZoomIn,
    ZoomOut,
    Loupe,
    LoupeZoomIn,
    LoupeZoomOut,
    Cross,
    Menu,
    List,
    List2,
    List3,
    Menu2,
    List4,
    Menu3,
    Exclamation,
    Question,
    Check,
    Cross2,
    Plus,
    Minus,
    Percent,
    ChevronUp,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsExpandVertical,
    ChevronsExpandHorizontal,
    ChevronsContractVertical,
    ChevronsContractHorizontal,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUpRight,
    ArrowsMerge,
    ArrowsSplit,
    ArrowDivert,
    ArrowReturn,
    Expand,
    Contract,
    Expand2,
    Contract2,
    Move,
    Tab,
    ArrowWave,
    Expand3,
    Expand4,
    Contract3,
    Notification,
    Warning,
    NotificationCircle,
    QuestionCircle,
    MenuCircle,
    CheckmarkCircle,
    CrossCircle,
    PlusCircle,
    CircleMinus,
    PercentCircle,
    ArrowUpCircle,
    ArrowDownCircle,
    ArrowLeftCircle,
    ArrowRightCircle,
    ChevronUpCircle,
    ChevronDownCircle,
    ChevronLeftCircle,
    ChevronRightCircle,
    BackwardCircle,
    FirstCircle,
    PreviousCircle,
    StopCircle,
    PlayCircle,
    PauseCircle,
    NextCircle,
    LastCircle,
    ForwardCircle,
    EjectCircle,
    Crop,
    FrameExpand,
    FrameContract,
    Focus,
    Transform,
    Grid,
    GridCrossed,
    Layers,
    LayersCrossed,
    Toggle,
    Rulers,
    Ruler,
    Funnel,
    FlipHorizontal,
    FlipVertical,
    FlipHorizontal2,
    FlipVertical2,
    Angle,
    Angle2,
    Subtract,
    Combine,
    Intersect,
    Exclude,
    AlignCenterVertical,
    AlignRight,
    AlignBottom,
    AlignLeft,
    AlignCenterHorizontal,
    AlignTop,
    Square,
    PlusSquare,
    MinusSquare,
    PercentSquare,
    ArrowUpSquare,
    ArrowDownSquare,
    ArrowLeftSquare,
    ArrowRightSquare,
    ChevronUpSquare,
    ChevronDownSquare,
    ChevronLeftSquare,
    ChevronRightSquare,
    CheckSquare,
    CrossSquare,
    MenuSquare,
    Prohibited,
    Circle,
    RadioButton,
    Ligature,
    TextFormat,
    TextFormatRemove,
    TextSize,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Highlight,
    TextAlignLeft,
    TextAlignCenter,
    TextAlignRight,
    TextAlignJustify,
    LineSpacing,
    IndentIncrease,
    IndentDecrease,
    TextWrap,
    Pilcrow,
    DirectionLtr,
    DirectionRtl,
    PageBreak,
    PageBreak2,
    SortAlphaAsc,
    SortAlphaDesc,
    SortNumericAsc,
    SortNumericDesc,
    SortAmountAsc,
    SortAmountDesc,
    SortTimeAsc,
    SortTimeDesc,
    Sigma,
    PencilLine,
    Hand,
    PointerUp,
    PointerRight,
    PointerDown,
    PointerLeft,
    FingerTap,
    FingersTap,
    Reminder,
    FingersCrossed,
    FingersVictory,
    GestureZoom,
    GesturePinch,
    FingersScrollHorizontal,
    FingersScrollVertical,
    FingersScrollLeft,
    FingersScrollRight,
    Hand2,
    PointerUp2,
    PointerRight2,
    PointerDown2,
    PointerLeft2,
    FingerTap2,
    FingersTap2,
    Reminder2,
    GestureZoom2,
    GesturePinch2,
    FingersScrollHorizontal2,
    FingersScrollVertical2,
    FingersScrollLeft2,
    FingersScrollRight2,
    FingersScrollVertical3,
    BorderStyle,
    BorderAll,
    BorderOuter,
    BorderInner,
    BorderTop,
    BorderHorizontal,
    BorderBottom,
    BorderLeft,
    BorderVertical,
    BorderRight,
    BorderNone,
    Ellipsis,
};
