/**
 * reactium-hooks.js file generated by arcli.
 * To develop this plugin, make your development changes to './index.js', not here.
 * Use `arcli plugin local` to activate local development, and `arcli plugin eject`
 */

import op from 'object-path';
import Reactium from 'reactium-core/sdk';

Reactium.Hook.register(
    'plugin-dependencies',
    async () => {
        const runtime = require('./reactium-hooks.json');

        if (op.get(runtime, 'development', false)) {
            Reactium.Plugin.unregister('shortcodes');

            // make your edits to index.js, not here
            require('./index');
        }
    },
    Reactium.Enums.priority.highest,
);
