/**
 * Generated by Reactium
 * DO NOT directly edit this file !!!!!!
 */

module.exports = {
    domains: {
        API: { name: 'API', implied: 'api', original: 'src/app/api/domain.js' },
        PickerTest: {
            name: 'PickerTest',
            implied: 'PickerTest',
            original: 'src/app/components/PickerTest/domain.js',
        },
        LoadingSpinner: {
            name: 'LoadingSpinner',
            implied: 'Loading',
            original: '.core/components/Loading/domain.js',
        },
        Blueprint: {
            name: 'Blueprint',
            implied: 'Blueprint',
            original:
                'reactium_modules/@atomic-reactor/reactium-admin-core/Blueprint/domain.js',
        },
        ReactiumUI: {
            name: 'ReactiumUI',
            implied: 'reactium-ui',
            original:
                'reactium_modules/@atomic-reactor/reactium-admin-core/reactium-ui/domain.js',
        },
    },
    relative: {
        'src/app/api': 'API',
        'src/app/components/PickerTest': 'PickerTest',
        '.core/components/Loading': 'LoadingSpinner',
        'reactium_modules/@atomic-reactor/reactium-admin-core/Blueprint':
            'Blueprint',
        'reactium_modules/@atomic-reactor/reactium-admin-core/reactium-ui':
            'ReactiumUI',
    },
};
