import PropTypes from 'prop-types';

export default {
    ID: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
    className: PropTypes.string,
    namespace: PropTypes.string,
    confirm: PropTypes.bool,
    data: PropTypes.object,
    debug: PropTypes.bool,
    delayFetch: PropTypes.number,
    directory: PropTypes.string,
    dismissable: PropTypes.bool,
    filter: PropTypes.func,
    filters: PropTypes.oneOfType([
        PropTypes.string,
        PropTypes.arrayOf(PropTypes.string),
    ]),
    itemsPerPage: PropTypes.number,
    maxSelect: PropTypes.number,
    minSelect: PropTypes.number,
    namespace: PropTypes.string,
    onCancel: PropTypes.func,
    onChange: PropTypes.func,
    onDismiss: PropTypes.func,
    onError: PropTypes.func,
    onInit: PropTypes.func,
    onItemSelect: PropTypes.func,
    onItemUnselect: PropTypes.func,
    onLoad: PropTypes.func,
    onMount: PropTypes.func,
    onStatus: PropTypes.func,
    onSubmit: PropTypes.func,
    onUnMount: PropTypes.func,
    page: PropTypes.number,
    pages: PropTypes.number,
    search: PropTypes.string,
    searchFields: PropTypes.arrayOf(PropTypes.string),
    selection: PropTypes.array,
    submitLabel: PropTypes.node,
    title: PropTypes.node,
    type: PropTypes.string,
};
